[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]

[package] 
name = "pdscan"
version = "0.1.0"

[package.build] 
backend = { name = "pixi-build-python", version = "==0.3.2" }

[package.host-dependencies]
hatchling = "==1.26.3"

[package.run-dependencies]
rich = "13.9.*"